### ISSUE TITLE
Typo in README, .register, but .add

### ISSUE THREAD

**Issue by dimparf** [xiaodongw/swagger-finatra#2]
You wrote register(new SwaggerController()) for Finatra 2, but this method with expected signature does not exists.
It should be .add(new SwaggerController()).
I found the correct line in your test (SampleApp.scala)

**Comment by xiaodongw** [comment]
It's the sample for Finatra 1.6 in document. Now updated it to have samples for both Finatra 1.6 and Finatra 2.1.
