### ISSUE TITLE
Not updated 0.3.0 on maven.

### ISSUE THREAD

**Issue by Nebu1eto** [xiaodongw/swagger-finatra#5]
Thanks for awesome project. :+1: 
I want to put in my project, but in maven it's still on 0.2.0

I think it should be update. Thanks.

**Comment by dimparf** [comment]
Hi, same problem. Maven repos does not contain artifact with version 0.3.0 only 0.1.0.

**Comment by xiaodongw** [comment]
This has been fixed, now 0.3.0 is published.

**Comment by Nebu1eto** [comment]
Thanks for upload. :D
