### ISSUE TITLE
Upgrade to Finatra 2.1.1

### ISSUE THREAD

**Issue by xiaodongw** [xiaodongw/swagger-finatra#6]
Finatra 2.1.1 is out, the break change is finagle-httpx is renamed back to finagle-http.

**Comment by enpuliu** [comment]
Please add the following methods to class OperationWrap in your enhancement, thanks.
 def description(value: String): Unit = {
    operation.setDescription(value)
  }

  def consumes(values: String*): Unit = {
    operation.setConsumes(values.asJava)
  }

  def produces(values: String*): Unit = {
    operation.setProduces(values.asJava)
  }

**Comment by xiaodongw** [comment]
@enpuliu Done, the methods you mentioned also got added.
