### ISSUE TITLE
Ability to specify JSON mapper

### ISSUE THREAD

**Issue by thepratt** [xiaodongw/swagger-finatra#7]
Currently you use the swagger json mapper, wouldn't it be better to use the included finatra mapper (with the option to use `@CamelCaseMapper`)? I use the default finatra functionality when it comes to mapping values, so my requests look like:

```
{
    "a_very_important": "value"
}
```

instead of

```
{
    "aVeryImportant": "value"
}
```

And I don't see a way currently to support the first without writing name annotations on every request case class. if you don't have time, are you open to a PR surrounding this?

**Comment by xiaodongw** [comment]
I tried to use Finatra's mapper without success, it still generated the camel cased property name.
Please feel free to open a PR for it, thanks.

**Comment by xiaodongw** [comment]
Updated API, now you can config the swagger JSON.

Please see the sample application for more information.

**Comment by thepratt** [comment]
Thanks for that Xiaodong. I'll update, and test it out later next week.
