### ISSUE TITLE
ApiModelProperty annotation unexpected result

### ISSUE THREAD

**Issue by joecwu** [xiaodongw/swagger-finatra#8]
I used swagger ApiModelProperty annotation in my Model declaration, but some fields in annotation not working in api-docs result e.g: `required`, `example`, `reference`, `allowableValues`.

Did I try something unimplemented featues? or it should work correctly? Thanks.

**Comment by xiaodongw** [comment]
I tested with required, example, allowableValues, dataType, readOnly, they all do work.

Please see my updated example, the class Course.

**Comment by xiaodongw** [comment]
I assume this is not a problem, closing it.
